### ISSUE TITLE
cannot assign logicMiddleware instance to multiple stores exception - during tests only

### ISSUE THREAD

**Issue by raythree** [jeffbski/redux-logic#86]
Hi, first off, thanks for this great project!

I'm trying to introduce redux-logic to my stack, and I'm getting this exception ONLY when running tests:
```
 FAIL  src/login/login.test.js
  sets the correct default state

    cannot assign logicMiddleware instance to multiple stores, create separate instance for each

      at mw (node_modules/redux-logic/build-lib/createLogicMiddleware.js:114:13)
      at node_modules/redux/lib/applyMiddleware.js:49:16
```
I do NOT get this when running in normal dev mode ```npm start```. I am using ```create-react-app``` as the starter kit. My ```configureStore``` method is pretty straight forward, and when running in dev I see that the logic process method is called. configureStore is setup as follows, with only 1 logic function at the moment:
```
import { createStore, compose, applyMiddleware } from 'redux';
import createHistory from 'history/createBrowserHistory';
import { routerMiddleware } from 'react-router-redux';
import { createLogicMiddleware } from 'redux-logic';

import rootReducer from './reducers';
import { loginLogic } from '../login';

export const history = createHistory();

const arrLogic = [loginLogic];
const logicMiddleware = createLogicMiddleware(arrLogic, {});

export default function configureStore(initialState) {
  const reactRouterMiddleware = routerMiddleware(history);
  const middlewares = [
    // Add other middleware here...
    logicMiddleware,
    reactRouterMiddleware
  ];

  let store = createStore(rootReducer, {}, compose(applyMiddleware(...middlewares)));
  return store;
}
```
When running tests they all fail due to the exception above. The test code is also pretty straight forward:
```
import { loggingIn, login, loggedIn, loginError } from './login'; // login action creators
import configureStore from '../store';

let store;

beforeEach(() => {
  store = configureStore();
});

test('exports login actions', () => {
  expect(typeof login).toBe('function');
  expect(typeof loggingIn).toBe('function');
  expect(typeof loggedIn).toBe('function');
  expect(typeof loginError).toBe('function');
});

test('sets the correct default state', () => {
  expect(store.getState().login).toEqual({
    pending: false,
    error: null,
    loggedIn: false
  });
});
```
Any idea why this is happening?

**Comment by jeffbski** [comment]
@raythree Thanks for writing. 

Yes, this is an easy fix. Currently logicMiddleware instances can only be used with a single store, so you just need to create new ones if you are creating new stores. 

With your above code, just bring the createLogicMiddleware into the configureStore call and you'll be good.

Also if you want to have access to the logicMiddleware instance for later use, then I usually hang it off the store for convenient use from anywhere you have access to the store. I demonstrate below.

```js
import { createStore, compose, applyMiddleware } from 'redux';
import createHistory from 'history/createBrowserHistory';
import { routerMiddleware } from 'react-router-redux';
import { createLogicMiddleware } from 'redux-logic';

import rootReducer from './reducers';
import { loginLogic } from '../login';

export const history = createHistory();

const arrLogic = [loginLogic];

export default function configureStore(initialState) {
  const reactRouterMiddleware = routerMiddleware(history);
  const logicMiddleware = createLogicMiddleware(arrLogic, {});
  const middlewares = [
    // Add other middleware here...
    logicMiddleware,
    reactRouterMiddleware
  ];

  let store = createStore(rootReducer, {}, compose(applyMiddleware(...middlewares)));

  // I often store the logicMiddleware as a property on the store for later use from anywhere
  // that I have access to the store. Now I can do store.logicMiddlware.addLogic() etc.
  store.logicMiddleware = logicMiddleware; // provide convenient access 
  return store;
}
```

**Comment by raythree** [comment]
Great thanks for the tip.
